[package]
name = "json-flat-parser"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[dependencies]
simdutf8 = { version = "0.1.4", optional = true }
indexmap = { version = "2.2.6" }
[features]
simdutf8 = ["dep:simdutf8"]
